add_lunch_combo Gummy_targa-userdebug
add_lunch_combo Gummy_spyder-userdebug
add_lunch_combo Gummy_solana-userdebug
add_lunch_combo Gummy_maserati-userdebug
add_lunch_combo Gummy_shadow-userdebug
add_lunch_combo Gummy_droid2-userdebug
add_lunch_combo Gummy_droid2we-userdebug
add_lunch_combo Gummy_venus2-userdebug
