add_lunch_combo Gummy_toro-userdebug
add_lunch_combo Gummy_maguro-userdebug
add_lunch_combo Gummy_crespo-userdebug
add_lunch_combo Gummy_crespo4g-userdebug
add_lunch_combo Gummy_wingray-userdebug
add_lunch_combo Gummy_targa-userdebug
add_lunch_combo Gummy_spyder-userdebug
