add_lunch_combo Gummy_toro-userdebug
add_lunch_combo Gummy_maguro-userdebug
add_lunch_combo Gummy_crespo-userdebug
add_lunch_combo Gummy_crespo4g-userdebug
add_lunch_combo Gummy_captivatemtd-userdebug
add_lunch_combo Gummy_fascinatemtd-userdebug
add_lunch_combo Gummy_galaxysmtd-userdebug
add_lunch_combo Gummy_wingray-userdebug
